// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string {
  const url = process.env["DATABASE_URL"];
  if (url) return url;
  // Prisma CLI (e.g. generate) loads this file without needing a live DB.
  if (process.argv.some((arg) => arg.includes("generate"))) {
    return "postgresql://build:build@127.0.0.1:5432/build";
  }
  throw new Error("DATABASE_URL is required");
}

function getDirectUrl(): string {
  return process.env["DIRECT_URL"] ?? getDatabaseUrl();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDatabaseUrl(),
    directUrl: getDirectUrl(),
  },
});
