import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const ALLOWLIST = [
  'getting-started.md',
  'installation.md',
  'templates.md',
  'collection-settings.md',
  'post-settings.md',
  'comments.md',
  'paywall-membership.md',
  'analytics.md',
  'account-billing.md',
  'troubleshooting.md',
  'known-squarespace-behaviors.md',
] as const

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const docsDir = path.resolve(__dirname, '../../docs')
const outFile = path.resolve(__dirname, '../src/lib/compiled-support-docs.ts')

function compile(): string {
  const sections: string[] = []
  for (const filename of ALLOWLIST) {
    const filePath = path.join(docsDir, filename)
    if (!fs.existsSync(filePath)) {
      throw new Error(`Support docs allowlist missing file: ${filename}`)
    }
    const body = fs.readFileSync(filePath, 'utf8').trim()
    sections.push(`# ${filename}\n\n${body}`)
  }
  return sections.join('\n\n---\n\n')
}

const compiled = compile()
const source = `/* eslint-disable */
// Generated by server/scripts/compile-support-docs.ts — do not edit by hand.
export const COMPILED_SUPPORT_DOCS: string = ${JSON.stringify(compiled)}
`
fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, source)
console.log(`[compile-support-docs] wrote ${outFile} (${compiled.length} chars)`)
